---
# 5 Access, Authentication and Authorization
# 5.1 Configure time-based job schedulers
# 5.1.1 Ensure cron daemon is enabled and running (Automated)
# 5.1.2 Ensure permissions on /etc/crontab are configured (Automated)
# 5.1.3 Ensure permissions on /etc/cron.hourly are configured (Automated)
# 5.1.4 Ensure permissions on /etc/cron.daily are configured (Automated)
# 5.1.5 Ensure permissions on /etc/cron.weekly are configured (Automated)
# 5.1.6 Ensure permissions on /etc/cron.monthly are configured (Automated)
# 5.1.7 Ensure permissions on /etc/cron.d are configured (Automated)
# 5.1.8 Ensure cron is restricted to authorized users (Automated)
# 5.1.9 Ensure at is restricted to authorized users (Automated)
# 5.2 Configure SSH Server
# 5.2.1 Ensure permissions on /etc/ssh/sshd_config are configured (Automated)
# 5.2.2 Ensure permissions on SSH private host key files are configured (Automated)
# 5.2.3 Ensure permissions on SSH public host key files are configured (Automated)
# 5.2.4 Ensure SSH LogLevel is appropriate (Automated)
# 5.2.5 Ensure SSH X11 forwarding is disabled (Automated)
# 5.2.6 Ensure SSH MaxAuthTries is set to 4 or less (Automated)
# 5.2.7 Ensure SSH IgnoreRhosts is enabled (Automated)
# 5.2.8 Ensure SSH HostbasedAuthentication is disabled (Automated)
# 5.2.9 Ensure SSH root login is disabled (Automated)
# 5.2.10 Ensure SSH PermitEmptyPasswords is disabled (Automated)
# 5.2.11 Ensure SSH PermitUserEnvironment is disabled (Automated)
# 5.2.12 Ensure only strong Ciphers are used (Automated)
# 5.2.13 Ensure only strong MAC algorithms are used (Automated)
# 5.2.14 Ensure only strong Key Exchange algorithms are used (Automated)
# 5.2.15 Ensure SSH Idle Timeout Interval is configured (Automated)
# 5.2.16 Ensure SSH LoginGraceTime is set to one minute or less (Automated)
# 5.2.17 Ensure SSH access is limited (Automated)
# 5.2.18 Ensure SSH warning banner is configured (Automated)
# 5.2.19 Ensure SSH PAM is enabled (Automated)
# 5.2.20 Ensure SSH AllowTcpForwarding is disabled (Automated)
# 5.2.21 Ensure SSH MaxStartups is configured (Automated)
# 5.2.22 Ensure SSH MaxSessions is limited (Automated)
# 5.3 Configure PAM
# 5.3.1 Ensure password creation requirements are configured (Automated)
# 5.3.2 Ensure lockout for failed password attempts is configured (Automated)
# 5.3.3 Ensure password reuse is limited (Automated)
# 5.3.4 Ensure password hashing algorithm is SHA-512 (Automated)
# 5.4 User Accounts and Environment
# 5.4.1 Set Shadow Password Suite Parameters
# 5.4.1.1 Ensure password expiration is 365 days or less (Automated)
# 5.4.1.2 Ensure minimum days between password changes is configured (Automated)
# 5.4.1.3 Ensure password expiration warning days is 7 or more (Automated)
# 5.4.1.4 Ensure inactive password lock is 30 days or less (Automated)
# 5.4.1.5 Ensure all users last password change date is in the past (Automated)
# 5.4.2 Ensure system accounts are secured (Automated)
# 5.4.3 Ensure default group for the root account is GID 0 (Automated)
# 5.4.4 Ensure default user umask is 027 or more restrictive (Automated)
# 5.4.5 Ensure default user shell timeout is 900 seconds or less (Automated)
# 5.5 Ensure root login is restricted to system console (Manual)
# 5.6 Ensure access to the su command is restricted (Automated)